CXXFLAGS=-g -O2 -DUNICODE -Wall -std=c++20 -I . -I include
LDFLAGS=-L . -ldwrite -static-libgcc -static-libstdc++
OBJ=$(shell find -name "*.cc" | sed -e 's/\.cc$$/.o/g') $(shell find src -name "*.cpp" | sed -e 's/\.cpp$$/.o/g')
TARGET=test.exe

.PHONY: all clean

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) -o $@ $^ $(LDFLAGS)

clean:
	$(RM) $(TARGET) $(OBJ)
